# Generated by Django 4.0.3 on 2022-04-13 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0005_pdffile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdffile',
            options={'ordering': ['id'], 'verbose_name': 'PDFFile', 'verbose_name_plural': 'PDFFiles'},
        ),
    ]
