# Generated by Django 4.0.3 on 2022-04-13 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0006_alter_pdffile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrtext',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.pdffile'),
        ),
    ]
