# Generated by Django 4.0.3 on 2022-04-13 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0007_alter_ocrtext_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OCRText',
        ),
    ]
