# Generated by Django 4.0.3 on 2022-04-13 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0009_delete_imagefile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PDFFile',
            new_name='File',
        ),
    ]
